### ISSUE TITLE
Door closing automatically

### ISSUE THREAD

**Issue by alonsojmnz** [alonsojmnz/cs386-a2.1#4]

**Comment by ryanluceroo** [comment]
Hey alonso, I will go ahead and take a look on the code. Thanks again.

**Comment by ryanluceroo** [comment]
@Aidan-Trujillo  What do you think should be done?

**Comment by ryanluceroo** [comment]
@alonsojmnz  I think we should refer to issue #45

**Comment by alonsojmnz** [comment]
Has been modified, issue is now pertaining to a bug elsewhere.
